vars_SWAT = {'SUB_KM - Area of Subbasin':{'code':'SUB_KM','file': 'sub', 'unit':'km2','inp': True, 'out': False},
             'HRUTOT - Total number of HRUs':{'code':'HRUTOT','file': 'sub','inp': True, 'out': False},
             'RAIN_YRS - Number of years of max monthly 0.5 h rainfall data used':{'code':'RAIN_YRS','file': 'wgn','inp': True, 'out': False,'info':'Data used to define RAIN_HHMX(1-12)'},
             'PRECIPITATION - Precipitation per day':{'code':'RAIN_YRS','file': 'wgn','unit':'mm','inp': True, 'out': False},
             'PLAPS - Precipitation lapse rate':{'code':'PLAPS','file': 'sub','unit':'mm H2O/km','inp': True, 'out': False, 'info':'positive = precipitation increases with increase in elevation, negative = precipitation decreases with increase in elevation'},
             'IRGAGE - Number of measured precipitation records': {'code': 'IRGAGE', 'file': 'sub', 'inp': True, 'out': False, 'info': 'within a subbasin'},
             'RCH - Reach number': {'code': 'RCH', 'file': 'rch', 'inp': False, 'out': True, 'info': ''},
             'GIS - GIS number': {'code': 'GIS', 'file': 'rch', 'inp': False, 'out': True, 'info':'Reprinted from water configuration file'},
             'FIGFILE - Name of watershed configuration file':{'code':'FIGFILE','file':'file.cio','inp':True,'out':False}
             'MON': {'code': 'MON', 'file': 'rch', 'inp': False, 'out': True},
             'AREA - Area drained by reach': {'code': 'AREA', 'file': 'rch', 'unit':'km2','inp': False, 'out': True},
             'FLOW_IN - Average daily streamflow': {'code': 'FLOW_IN', 'file': 'rch', 'unit':'m3/s','inp': False, 'out': True,'info':'Average daily streamflow into reach, during timestep'},
             'FLOW_OUT': {'code': 'FLOW_OUT', 'file': 'rch', 'inp': False, 'out': True, 'dims': (8, 1)},
             'EVAP': {'code': 'EVAP', 'file': 'rch', 'inp': False, 'out': True},
             'TLOSS': {'code': 'TLOSS', 'file': 'rch', 'inp': False, 'out': True},
             'SED_IN': {'code': 'SED_IN', 'file': 'rch', 'inp': False, 'out': True},
             'SED_OUT': {'code': 'SED_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'SEDCONC': {'code': 'SEDCONC', 'file': 'rch', 'inp': False, 'out': True},
             'ORGN_IN': {'code': 'ORGN_IN', 'file': 'rch', 'inp': False, 'out': True},
             'ORGN_OUT': {'code': 'ORGN_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'ORGP_IN': {'code': 'ORGP_IN', 'file': 'rch', 'inp': False, 'out': True},
             'ORGP_OUT': {'code': 'ORGP_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'NO3_IN': {'code': 'NO3_IN', 'file': 'rch', 'inp': False, 'out': True},
             'NO3_OUT': {'code': 'NO3_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'NH4_IN': {'code': 'NH4_IN', 'file': 'rch', 'inp': False, 'out': True},
             'NH4_OUT': {'code': 'NH4_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'NO2_IN': {'code': 'NO2_IN', 'file': 'rch', 'inp': False, 'out': True},
             'NO2_OUT': {'code': 'NO2_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'MINP_IN': {'code': 'MINP_IN', 'file': 'rch', 'inp': False, 'out': True},
             'MINP_OUT': {'code': 'MINP_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'ALGAE_IN': {'code': 'ALGAE_IN', 'file': 'rch', 'inp': False, 'out': True},
             'ALGAE_OUT': {'code': 'ALGAE_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'CBOD_IN': {'code': 'CBOD_IN', 'file': 'rch', 'inp': False, 'out': True},
             'CBOD_OUT': {'code': 'CBOD_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'DISOX_IN': {'code': 'DISOX_IN', 'file': 'rch', 'inp': False, 'out': True},
             'DISOX_OUT': {'code': 'DISOX_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'SOLPST_IN': {'code': 'SOLPST_IN', 'file': 'rch', 'inp': False, 'out': True},
             'SOLPST_OUT': {'code': 'SOLPST_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'SORPST_IN': {'code': 'SORPST_IN', 'file': 'rch', 'inp': False, 'out': True},
             'SORPST_OUT': {'code': 'SORPST_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'REACTPST': {'code': 'REACTPST', 'file': 'rch', 'inp': False, 'out': True},
             'VOLPST': {'code': 'VOLPST', 'file': 'rch', 'inp': False, 'out': True},
             'SETTLPST': {'code': 'SETTLPST', 'file': 'rch', 'inp': False, 'out': True},
             'RESUSP_PST': {'code': 'RESUSP_PST', 'file': 'rch', 'inp': False, 'out': True},
             'DIFFUSEPST': {'code': 'DIFFUSEPST', 'file': 'rch', 'inp': False, 'out': True},
             'REACBEDPST': {'code': 'REACBEDPST', 'file': 'rch', 'inp': False, 'out': True},
             'BURYPST': {'code': 'BURYPST', 'file': 'rch', 'inp': False, 'out': True},
             'BED_PST': {'code': 'BED_PST', 'file': 'rch', 'inp': False, 'out': True},
             'BACTP_OUT': {'code': 'BACTP_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'BACTLP_OUT': {'code': 'BACTLP_OUT', 'file': 'rch', 'inp': False, 'out': True},
             'CMETAL#1': {'code': 'CMETAL#1', 'file': 'rch', 'inp': False, 'out': True},
             'CMETAL#2': {'code': 'CMETAL#2', 'file': 'rch', 'inp': False, 'out': True},
             'CMETAL#3': {'code': 'CMETAL#3', 'file': 'rch', 'inp': False, 'out': True},
             'TOT_N': {'code': 'TOT_N', 'file': 'rch', 'inp': False, 'out': True},
             'TOT_P': {'code': 'TOT_P', 'file': 'rch', 'inp': False, 'out': True},
             'NO3CONC': {'code': 'NO3CONC', 'file': 'rch', 'inp': False, 'out': True},
             'SFTMP - Snowfall temperature': {'code': 'SFTMP', 'file': 'bsn', 'unit':'Degrees C','inp': True, 'out': False},
             'SMTMP - Snow melt base temperature': {'code': 'SMTMP', 'file': 'bsn', 'unit': 'Degrees C','inp': True, 'out': False},
             'SMFMX - Snow melt factor (June 21)': {'code': 'SMFMX', 'file': 'bsn', 'unit':'mm H2O/ degrees C-day','inp': True, 'out': False},
             'SMFMN - Snow met factor (Dec. 21)': {'code': 'SMFMN', 'file': 'bsn', 'unit':'mm H2O/ degrees C-day', 'inp': True, 'out': False},
             'TIMP - Snow pack temperature lag factor': {'code': 'TIMP', 'file': 'bsn', 'inp': True, 'out': False},
             'SNOCOVMX - Min. snow water content': {'code': 'SNOCOVMX', 'file': 'bsn', 'unit':'mm H2O','inp': True, 'out': False, 'info':'Corresponds to 100% snow cover'},
             'SNO50COV - Fraction of snow volume': {'code': 'SNO50COV', 'file': 'bsn', 'inp': True, 'out': False, 'info':'Represented by SNOCOVMX and corresponding to 50% snow cover'},
             'SNO_SUB - Initial snow water content':{'code':'SNO_SUB', 'file':'sub', 'unit':'mm H2O', 'inp': True, 'out': False},
             'IPET': {'code': 'IPET', 'file': 'bsn', 'inp': True, 'out': False},
             'PETFILE': {'code': 'PETFILE', 'file': 'bsn', 'inp': True, 'out': False},
             'ESCO': {'code': 'ESCO', 'file': 'bsn', 'inp': True, 'out': False},
             'EPCO': {'code': 'EPCO', 'file': 'bsn', 'inp': True, 'out': False},
             'EVLAI': {'code': 'EVLAI', 'file': 'bsn', 'inp': True, 'out': False},
             'FFCB': {'code': 'FFCB', 'file': 'bsn', 'inp': True, 'out': False},
             'IEVENT - Rainfall/ runoff/ routing option ': {'code': 'IEVENT', 'file': 'bsn', 'inp': True, 'out': False, 'info':'0,1,2 or 3'},
             'ICRK': {'code': 'ICRK', 'file': 'bsn', 'inp': True, 'out': False},
             'SURLAG': {'code': 'SURLAG', 'file': 'bsn', 'inp': True, 'out': False},
             'ADJ_PKR': {'code': 'ADJ_PKR', 'file': 'bsn', 'inp': True, 'out': False},
             'PRF_BSN': {'code': 'PRF_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'SPCON': {'code': 'SPCON', 'file': 'bsn', 'inp': True, 'out': False},
             'SPEXP': {'code': 'SPEXP', 'file': 'bsn', 'inp': True, 'out': False},
             'RCN': {'code': 'RCN', 'file': 'bsn', 'inp': True, 'out': False},
             'CMN': {'code': 'CMN', 'file': 'bsn', 'inp': True, 'out': False},
             'N_UPDIS': {'code': 'N_UPDIS', 'file': 'bsn', 'inp': True, 'out': False},
             'P_UPDIS': {'code': 'P_UPDIS', 'file': 'bsn', 'inp': True, 'out': False},
             'NPERCO': {'code': 'NPERCO', 'file': 'bsn', 'inp': True, 'out': False},
             'PPERCO': {'code': 'PPERCO', 'file': 'bsn', 'inp': True, 'out': False},
             'PHOSKD': {'code': 'PHOSKD', 'file': 'bsn', 'inp': True, 'out': False},
             'PSP': {'code': 'PSP', 'file': 'bsn', 'inp': True, 'out': False},
             'RSDCO': {'code': 'RSDCO', 'file': 'bsn', 'inp': True, 'out': False},
             'PERCOP': {'code': 'PERCOP', 'file': 'bsn', 'inp': True, 'out': False},
             'ISUBWQ': {'code': 'ISUBWQ', 'file': 'bsn', 'inp': True, 'out': False},
             'WDPQ': {'code': 'WDPQ', 'file': 'bsn', 'inp': True, 'out': False},
             'WGPQ': {'code': 'WGPQ', 'file': 'bsn', 'inp': True, 'out': False},
             'WDLPQ': {'code': 'WDLPQ', 'file': 'bsn', 'inp': True, 'out': False},
             'WGLPQ': {'code': 'WGLPQ', 'file': 'bsn', 'inp': True, 'out': False},
             'WDPS': {'code': 'WDPS', 'file': 'bsn', 'inp': True, 'out': False},
             'WGPS': {'code': 'WGPS', 'file': 'bsn', 'inp': True, 'out': False},
             'WDLPS': {'code': 'WDLPS', 'file': 'bsn', 'inp': True, 'out': False},
             'WGLPS': {'code': 'WGLPS', 'file': 'bsn', 'inp': True, 'out': False},
             'BACTKDQ': {'code': 'BACTKDQ', 'file': 'bsn', 'inp': True, 'out': False},
             'THBACT': {'code': 'THBACT', 'file': 'bsn', 'inp': True, 'out': False},
             'WOF_P': {'code': 'WOF_P', 'file': 'bsn', 'inp': True, 'out': False},
             'WOF_LP': {'code': 'WOF_LP', 'file': 'bsn', 'inp': True, 'out': False},
             'WDPF': {'code': 'WDPF', 'file': 'bsn', 'inp': True, 'out': False},
             'WGPF': {'code': 'WGPF', 'file': 'bsn', 'inp': True, 'out': False},
             'WDLPF': {'code': 'WDLPF', 'file': 'bsn', 'inp': True, 'out': False},
             'WGLPF': {'code': 'WGLPF', 'file': 'bsn', 'inp': True, 'out': False},
             'ISED_DET - Daily max 0.5 h rainfall value calculation code': {'code': 'ISED_DET', 'file': 'bsn', 'inp': True, 'out': False,'info':'0 = generation of daily value using triangular distribution, 1 = use of monthly max half-hour rainfall value for all days in month'},
             'IRTE': {'code': 'IRTE', 'file': 'bsn', 'inp': True, 'out': False},
             'MSK_CO1': {'code': 'MSK_CO1', 'file': 'bsn', 'inp': True, 'out': False},
             'MSK_CO2': {'code': 'MSK_CO2', 'file': 'bsn', 'inp': True, 'out': False},
             'MSK_X': {'code': 'MSK_X', 'file': 'bsn', 'inp': True, 'out': False},
             'IDEG': {'code': 'IDEG', 'file': 'bsn', 'inp': True, 'out': False},
             'IWQ': {'code': 'IWQ', 'file': 'bsn', 'inp': True, 'out': False},
             'WWQFILE': {'code': 'WWQFILE', 'file': 'bsn', 'inp': True, 'out': False},
             'TRNSRCH': {'code': 'TRNSRCH', 'file': 'bsn', 'inp': True, 'out': False},
             'EVRCH': {'code': 'EVRCH', 'file': 'bsn', 'inp': True, 'out': False},
             'IRTPEST': {'code': 'IRTPEST', 'file': 'bsn', 'inp': True, 'out': False},
             'ICN': {'code': 'ICN', 'file': 'bsn', 'inp': True, 'out': False},
             'CNCOEF': {'code': 'CNCOEF', 'file': 'bsn', 'inp': True, 'out': False},
             'CDN': {'code': 'CDN', 'file': 'bsn', 'inp': True, 'out': False},
             'SDNCO': {'code': 'SDNCO', 'file': 'bsn', 'inp': True, 'out': False},
             'BACT_SWF': {'code': 'BACT_SWF', 'file': 'bsn', 'inp': True, 'out': False},
             'BACTMX': {'code': 'BACTMX', 'file': 'bsn', 'inp': True, 'out': False},
             'BACTMINLP': {'code': 'BACTMINLP', 'file': 'bsn', 'inp': True, 'out': False},
             'BACTMINP': {'code': 'BACTMINP', 'file': 'bsn', 'inp': True, 'out': False},
             'WDLPRCH': {'code': 'WDLPRCH', 'file': 'bsn', 'inp': True, 'out': False},
             'WDPRCH': {'code': 'WDPRCH', 'file': 'bsn', 'inp': True, 'out': False},
             'WDLPRES': {'code': 'WDLPRES', 'file': 'bsn', 'inp': True, 'out': False},
             'WDPRES': {'code': 'WDPRES', 'file': 'bsn', 'inp': True, 'out': False},
             'TB_ADJ': {'code': 'TB_ADJ', 'file': 'bsn', 'inp': True, 'out': False},
             'DEPIMP_BSN': {'code': 'DEPIMP_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'DDRAIN_BSN': {'code': 'DDRAIN_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'TDRAIN_BSN': {'code': 'TDRAIN_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'GDRAIN_BSN': {'code': 'GDRAIN_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'CN_FROZ': {'code': 'CN_FROZ', 'file': 'bsn', 'inp': True, 'out': False},
             'DORM_HR': {'code': 'DORM_HR', 'file': 'bsn', 'inp': True, 'out': False},
             'SMXCO': {'code': 'SMXCO', 'file': 'bsn', 'inp': True, 'out': False},
             'FIXCO': {'code': 'FIXCO', 'file': 'bsn', 'inp': True, 'out': False},
             'NFIXMX': {'code': 'NFIXMX', 'file': 'bsn', 'inp': True, 'out': False},
             'ANION_EXCL_BSN': {'code': 'ANION_EXCL_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'CH_ONCO_BSN': {'code': 'CH_ONCO_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'CH_OPCO_BSN': {'code': 'CH_OPCO_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'HLIFE_NGW_BSN': {'code': 'HLIFE_NGW_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'RCN_SUB_BSN': {'code': 'RCN_SUB_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'BC1_BSN': {'code': 'BC1_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'BC2_BSN': {'code': 'BC2_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'BC3_BSN': {'code': 'BC3_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'BC4_BSN': {'code': 'BC4_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'DECR_MIN': {'code': 'DECR_MIN', 'file': 'bsn', 'inp': True, 'out': False},
             'ICFAC': {'code': 'ICFAC', 'file': 'bsn', 'inp': True, 'out': False},
             'RSD_COVCO': {'code': 'RSD_COVCO', 'file': 'bsn', 'inp': True, 'out': False},
             'VCRIT': {'code': 'VCRIT', 'file': 'bsn', 'inp': True, 'out': False},
             'CSWAT': {'code': 'CSWAT', 'file': 'bsn', 'inp': True, 'out': False},
             'RES_STLR_CO': {'code': 'RES_STLR_CO', 'file': 'bsn', 'inp': True, 'out': False},
             'BFLO_DIST 0-1 (1': {'code': 'BFLO_DIST 0-1 (1', 'file': 'bsn', 'inp': True, 'out': False},
             'IUH': {'code': 'IUH', 'file': 'bsn', 'inp': True, 'out': False},
             'UHALPHA': {'code': 'UHALPHA', 'file': 'bsn', 'inp': True, 'out': False},
             'EROS_SPL': {'code': 'EROS_SPL', 'file': 'bsn', 'inp': True, 'out': False},
             'RILL_MULT': {'code': 'RILL_MULT', 'file': 'bsn', 'inp': True, 'out': False},
             'EROS_EXPO': {'code': 'EROS_EXPO', 'file': 'bsn', 'inp': True, 'out': False},
             'SUBD_CHSED': {'code': 'SUBD_CHSED', 'file': 'bsn', 'inp': True, 'out': False},
             'C_FACTOR': {'code': 'C_FACTOR', 'file': 'bsn', 'inp': True, 'out': False},
             'CH_D50': {'code': 'CH_D50', 'file': 'bsn', 'inp': True, 'out': False},
             'SIG_G': {'code': 'SIG_G', 'file': 'bsn', 'inp': True, 'out': False},
             'RE_BSN': {'code': 'RE_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'SDRAIN_BSN': {'code': 'SDRAIN_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'DRAIN_CO_BSN': {'code': 'DRAIN_CO_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'PC_BSN': {'code': 'PC_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'LATKSATF_BSN': {'code': 'LATKSATF_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'ITDRN': {'code': 'ITDRN', 'file': 'bsn', 'inp': True, 'out': False},
             'IWTDN': {'code': 'IWTDN', 'file': 'bsn', 'inp': True, 'out': False},
             'SOL_P_MODEL': {'code': 'SOL_P_MODEL', 'file': 'bsn', 'inp': True, 'out': False},
             'IABSTR': {'code': 'IABSTR', 'file': 'bsn', 'inp': True, 'out': False},
             'IATMODEP': {'code': 'IATMODEP', 'file': 'bsn', 'inp': True, 'out': False},
             'R2ADJ_BSN': {'code': 'R2ADJ_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'SSTMAXD_BSN': {'code': 'SSTMAXD_BSN', 'file': 'bsn', 'inp': True, 'out': False},
             'ISMAX': {'code': 'ISMAX', 'file': 'bsn', 'inp': True, 'out': False},
             'IROUTUNIT': {'code': 'IROUTUNIT', 'file': 'bsn', 'inp': True, 'out': False},
             'NMGT': {'code': 'NMGT', 'file': 'mgt', 'inp': True, 'out': False},
             'IGRO': {'code': 'IGRO', 'file': 'mgt', 'inp': True, 'out': False},
             'PLANT_ID': {'code': 'PLANT_ID', 'file': 'mgt', 'inp': True, 'out': False},
             'LAI_INIT': {'code': 'LAI_INIT', 'file': 'mgt', 'inp': True, 'out': False},
             'BIO_INIT': {'code': 'BIO_INIT', 'file': 'mgt', 'inp': True, 'out': False},
             'PHU_PLT': {'code': 'PHU_PLT', 'file': 'mgt', 'inp': True, 'out': False},
             'BIOMIX': {'code': 'BIOMIX', 'file': 'mgt', 'inp': True, 'out': False},
             'CN2': {'code': 'CN2', 'file': 'mgt', 'inp': True, 'out': False},
             'USLE_P': {'code': 'USLE_P', 'file': 'mgt', 'inp': True, 'out': False},
             'BIO_MIN': {'code': 'BIO_MIN', 'file': 'mgt', 'inp': True, 'out': False},
             'FILTERW': {'code': 'FILTERW', 'file': 'mgt', 'inp': True, 'out': False},
             'IURBAN': {'code': 'IURBAN', 'file': 'mgt', 'inp': True, 'out': False},
             'URBLU': {'code': 'URBLU', 'file': 'mgt', 'inp': True, 'out': False},
             'IRRSC': {'code': 'IRRSC', 'file': 'mgt', 'inp': True, 'out': False},
             'IRRNO': {'code': 'IRRNO', 'file': 'mgt', 'inp': True, 'out': False},
             'FLOWMIN': {'code': 'FLOWMIN', 'file': 'mgt', 'inp': True, 'out': False},
             'DIVMAX': {'code': 'DIVMAX', 'file': 'mgt', 'inp': True, 'out': False},
             'FLOWFR': {'code': 'FLOWFR', 'file': 'mgt', 'inp': True, 'out': False},
             'DDRAIN': {'code': 'DDRAIN', 'file': 'mgt', 'inp': True, 'out': False},
             'TDRAIN': {'code': 'TDRAIN', 'file': 'mgt', 'inp': True, 'out': False},
             'GDRAIN': {'code': 'GDRAIN', 'file': 'mgt', 'inp': True, 'out': False},
             'NROT': {'code': 'NROT', 'file': 'mgt', 'inp': True, 'out': False},
             'NBYR - Number of simulated years': {'code': 'NBYR', 'file': 'file.cio', 'inp': True, 'out': False},
             'IYR - Beginning year of simulation': {'code': 'IYR', 'file': 'file.cio', 'inp': True, 'out': False},
             'IDAF - Beginning day of simulation': {'code': 'IDAF', 'file': 'file.cio', 'inp': True, 'out': False},
             'IDAL - Ending day of simulation': {'code': 'IDAL', 'file': 'file.cio', 'inp': True, 'out': False},
             'IGEN - Random generator seed code': {'code': 'IGEN', 'file': 'file.cio', 'inp': True, 'out': False},
             'PCPSIM - Rainfall input code': {'code': 'PCPSIM', 'file': 'file.cio', 'inp': True, 'out': False, 'info': '1 = measured data, 2 = generated rainfall'},
             'IDT - Measured rainfall data timestep': {'code': 'IDT', 'file': 'file.cio', 'units':'minutes','inp': True, 'out': False},
             'IDIST - Rainfall distribution code': {'code': 'IDIST', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Used to generate daily precipitation values. 0 = skewed distribution, 1 = mixed exponential distribution'},
             'REXP - Exponent of mixed exponential rainfall distribution': {'code': 'REXP', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Used if IDIST=1. REXP=1.3 if no value is entered.'},
             'NRGAGE - Number of precipitation gage files': {'code': 'NRGAGE', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 18 files'},
             'NRTOT - Total number of precipitation gage records': {'code': 'NRTOT', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 5400 records'},
             'NRGFIL - Number of precipitation records per file': {'code': 'NRGFIL', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 300 records/file'},
             'RFILE(1) - Name of precipitation input file 1': {'code': 'RFILE(1)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(2) - Name of precipitation input file 2': {'code': 'RFILE(2)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(3) - Name of precipitation input file 3': {'code': 'RFILE(3)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(4) - Name of precipitation input file 4': {'code': 'RFILE(4)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(5) - Name of precipitation input file 5': {'code': 'RFILE(5)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(6) - Name of precipitation input file 6': {'code': 'RFILE(6)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(7) - Name of precipitation input file 7': {'code': 'RFILE(7)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(8) - Name of precipitation input file 8': {'code': 'RFILE(8)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(9) - Name of precipitation input file 9': {'code': 'RFILE(9)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(10) - Name of precipitation input file 10': {'code': 'RFILE(10)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(11) - Name of precipitation input file 11': {'code': 'RFILE(11)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(12) - Name of precipitation input file 12': {'code': 'RFILE(12)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(13) - Name of precipitation input file 13': {'code': 'RFILE(13)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(14) - Name of precipitation input file 14': {'code': 'RFILE(14)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(15) - Name of precipitation input file 15': {'code': 'RFILE(15)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(16) - Name of precipitation input file 16': {'code': 'RFILE(16)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(17) - Name of precipitation input file 17': {'code': 'RFILE(17)', 'file': 'file.cio', 'inp': True, 'out': False},
             'RFILE(18) - Name of precipitation input file 18': {'code': 'RFILE(18)', 'file': 'file.cio', 'inp': True, 'out': False},
             'TMPSIM - Temperature input code': {'code': 'TMPSIM', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'1 = measure date read, 2 = daily max/min generated'},
             'NTGAGE - Number of temperature gage files': {'code': 'NTGAGE', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 18 files'},
             'NTTOT - Total number of temperature gage records': {'code': 'NTTOT', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 2700 records'},
             'NTGFIL - Number of temperature gage records per file': {'code': 'NTGFIL', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 150 records per file'},
             'MAX TEMP - Daily maximum temperature': {'code':'MAX TEMP', 'file':'tmp', 'unit':'Degrees C', 'inp': True, 'out': False},
             'MIN TEMP - Daily minimum temperature': {'code':'MIN TEMP', 'file':'tmp', 'unit':'Degrees C', 'inp': True, 'out': False},
             'ITGAGE - Number of measured temperature record within subbasin': {'code':'ITGAGE', 'file':'sub','inp': True, 'out': False},
             'TLAPS - Temperature lapse rate': {'code':'TLAPS', 'file':'sub', 'unit':'Degrees C/km','inp': True, 'out': False},
             'SLRSIM - Solar radiation input code': {'code': 'SLRSIM', 'file': 'file.cio', 'inp': True, 'out': False, 'info': '1 = measured data, 2 = generated solar radiation'},
             'NSTOT - Number of solar radiation records': {'code': 'NSTOT', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 300 records'},
             'RHSIM - Relative humidity input code': {'code': 'RHSIM', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'1 = measured data, 2 = generated relative humidity'},
             'NHTOT - Number of relative humidity records': {'code': 'NHTOT', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'Up to 300 records'},
             'WINDSIM': {'code': 'WINDSIM', 'file': 'file.cio', 'inp': True, 'out': False},
             'NWTOT': {'code': 'NWTOT', 'file': 'file.cio', 'inp': True, 'out': False},
             'FCSTYR': {'code': 'FCSTYR', 'file': 'file.cio', 'inp': True, 'out': False},
             'FCSTDAY': {'code': 'FCSTDAY', 'file': 'file.cio', 'inp': True, 'out': False},
             'FCSTCYCLES': {'code': 'FCSTCYCLES', 'file': 'file.cio', 'inp': True, 'out': False},
             'SLRFILE - Name of measured solar radiation input file': {'code': 'SLRFILE', 'file': 'file.cio', 'inp': True, 'out': False},
             'WLATITUDE - Latitude of weather station': {'code': 'WLATITUDE', 'file': 'wgn', 'unit':'Degrees','inp': True, 'out': False},
             'SOL_RAD - Daily total radiation': {'code': 'SOL_RAD', 'file': 'slr', 'unit':'MJ/m2','inp': True, 'out': False},
             'ISGAGE - Number of solar radiation records within subbasin': {'code': 'ISGAGE', 'file': 'sub', 'inp': True, 'out': False},
             'RHFILE - Name of measured relative humidity input file': {'code': 'RHFILE', 'file': 'file.cio', 'inp': True, 'out': False},
             'WNDFILE': {'code': 'WNDFILE', 'file': 'file.cio', 'inp': True, 'out': False},
             'FCSTFILE': {'code': 'FCSTFILE', 'file': 'file.cio', 'inp': True, 'out': False},
             'BSNFILE': {'code': 'BSNFILE', 'file': 'file.cio', 'inp': True, 'out': False},
             'PLANTDB': {'code': 'PLANTDB', 'file': 'file.cio', 'inp': True, 'out': False},
             'TILLDB': {'code': 'TILLDB', 'file': 'file.cio', 'inp': True, 'out': False},
             'PESTDB': {'code': 'PESTDB', 'file': 'file.cio', 'inp': True, 'out': False},
             'FERTDB': {'code': 'FERTDB', 'file': 'file.cio', 'inp': True, 'out': False},
             'URBANDB': {'code': 'URBANDB', 'file': 'file.cio', 'inp': True, 'out': False},
             'ISPROJ - Special project flag': {'code': 'ISPROJ', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'0 = not special project, 1 = repeat simulation'},
             'ICLB': {'code': 'ICLB', 'file': 'file.cio', 'inp': True, 'out': False},
             'CALFILE': {'code': 'CALFILE', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPRINT - Print code': {'code': 'IPRINT', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'0 = monthly,1 = daily, 2 = annually'},
             'NYSKIP - Number of years of skipped output': {'code': 'NYSKIP', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'0 print all years, 1 print after 1st year, 2 after 2nd, etc.'},
             'ILOG - Streamflow print code': {'code': 'ILOG', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'0 = print streamflow, 1 = print log streamflow'},
             'IPRP - Output.pst print code': {'code': 'IPRP', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'0 = do not print, 1 = print'},
             'IPRS - Soil chemical output print code': {'code': 'IPRS', 'file': 'file.cio', 'inp': True, 'out': False, 'info':'0 = do not print, 1 = print'},
             'IPDVAR(1) - Printed output variable 1 (.rch)': {'code': 'IPDVAR(1)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(2) - Printed output variable 2 (.rch)': {'code': 'IPDVAR(2)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(3) - Printed output variable 3 (.rch)': {'code': 'IPDVAR(3)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(4) - Printed output variable 4 (.rch)': {'code': 'IPDVAR(4)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(5) - Printed output variable 5 (.rch)': {'code': 'IPDVAR(5)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(6) - Printed output variable 6 (.rch)': {'code': 'IPDVAR(6)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(7) - Printed output variable 7 (.rch)': {'code': 'IPDVAR(7)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(8) - Printed output variable 8 (.rch)': {'code': 'IPDVAR(8)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(9) - Printed output variable 9 (.rch)': {'code': 'IPDVAR(9)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(10) - Printed output variable 10 (.rch)': {'code': 'IPDVAR(10)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(11) - Printed output variable 11 (.rch)': {'code': 'IPDVAR(11)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(12) - Printed output variable 12 (.rch)': {'code': 'IPDVAR(12)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(13) - Printed output variable 13 (.rch)': {'code': 'IPDVAR(13)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(14) - Printed output variable 14 (.rch)': {'code': 'IPDVAR(14)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(15) - Printed output variable 15 (.rch)': {'code': 'IPDVAR(15)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(16) - Printed output variable 16 (.rch)': {'code': 'IPDVAR(16)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(17) - Printed output variable 17 (.rch)': {'code': 'IPDVAR(17)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(18) - Printed output variable 18 (.rch)': {'code': 'IPDVAR(18)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(19) - Printed output variable 19 (.rch)': {'code': 'IPDVAR(19)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAR(20) - Printed output variable 20 (.rch)': {'code': 'IPDVAR(20)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(1) - Printed output variable 1 (.sub)': {'code': 'IPDVAB(1)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(2) - Printed output variable 2 (.sub)': {'code': 'IPDVAB(2)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(3) - Printed output variable 3 (.sub)': {'code': 'IPDVAB(3)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(4) - Printed output variable 4 (.sub)': {'code': 'IPDVAB(4)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(5) - Printed output variable 5 (.sub)': {'code': 'IPDVAB(5)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(6) - Printed output variable 6 (.sub)': {'code': 'IPDVAB(6)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(7) - Printed output variable 7 (.sub)': {'code': 'IPDVAB(7)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(8) - Printed output variable 8 (.sub)': {'code': 'IPDVAB(8)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(9) - Printed output variable 9 (.sub)': {'code': 'IPDVAB(9)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(10) - Printed output variable 10 (.sub)': {'code': 'IPDVAB(10)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(11) - Printed output variable 11 (.sub)': {'code': 'IPDVAB(11)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(12) - Printed output variable 12 (.sub)': {'code': 'IPDVAB(12)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(13) - Printed output variable 13 (.sub)': {'code': 'IPDVAB(13)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(14) - Printed output variable 14 (.sub)': {'code': 'IPDVAB(14)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(15) - Printed output variable 15 (.sub)': {'code': 'IPDVAB(15)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(16) - Printed output variable 16 (.sub)': {'code': 'IPDVAB(16)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(17) - Printed output variable 17 (.sub)': {'code': 'IPDVAB(17)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(18) - Printed output variable 18 (.sub)': {'code': 'IPDVAB(18)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(19) - Printed output variable 19 (.sub)': {'code': 'IPDVAB(19)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAB(20) - Printed output variable 20 (.sub)': {'code': 'IPDVAB(20)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(1) - Printed output variable 1 (.hru)': {'code': 'IPDVAS(1)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(2) - Printed output variable 2 (.hru)': {'code': 'IPDVAS(2)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(3) - Printed output variable 3 (.hru)': {'code': 'IPDVAS(3)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(4) - Printed output variable 4 (.hru)': {'code': 'IPDVAS(4)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(5) - Printed output variable 5 (.hru)': {'code': 'IPDVAS(5)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(6) - Printed output variable 6 (.hru)': {'code': 'IPDVAS(6)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(7) - Printed output variable 7 (.hru)': {'code': 'IPDVAS(7)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(8) - Printed output variable 8 (.hru)': {'code': 'IPDVAS(8)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(9) - Printed output variable 9 (.hru)': {'code': 'IPDVAS(9)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(10) - Printed output variable 10 (.hru)': {'code': 'IPDVAS(10)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(11) - Printed output variable 11 (.hru)': {'code': 'IPDVAS(11)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(12) - Printed output variable 12 (.hru)': {'code': 'IPDVAS(12)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(13) - Printed output variable 13 (.hru)': {'code': 'IPDVAS(13)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(14) - Printed output variable 14 (.hru)': {'code': 'IPDVAS(14)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(15) - Printed output variable 15 (.hru)': {'code': 'IPDVAS(15)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(16) - Printed output variable 16 (.hru)': {'code': 'IPDVAS(16)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(17) - Printed output variable 17 (.hru)': {'code': 'IPDVAS(17)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(18) - Printed output variable 18 (.hru)': {'code': 'IPDVAS(18)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(19) - Printed output variable 19 (.hru)': {'code': 'IPDVAS(19)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDVAS(20) - Printed output variable 20 (.hru)': {'code': 'IPDVAS(20)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(1) - Printed output data of HRU 1': {'code': 'IPDHRU(1)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(2) - Printed output data of HRU 2': {'code': 'IPDHRU(2)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(3) - Printed output data of HRU 3': {'code': 'IPDHRU(3)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(4) - Printed output data of HRU 4': {'code': 'IPDHRU(4)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(5) - Printed output data of HRU 5': {'code': 'IPDHRU(5)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(6) - Printed output data of HRU 6': {'code': 'IPDHRU(6)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(7) - Printed output data of HRU 7': {'code': 'IPDHRU(7)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(8) - Printed output data of HRU 8': {'code': 'IPDHRU(8)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(9) - Printed output data of HRU 9': {'code': 'IPDHRU(9)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(10) - Printed output data of HRU 10': {'code': 'IPDHRU(10)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(11) - Printed output data of HRU 11': {'code': 'IPDHRU(11)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(12) - Printed output data of HRU 12': {'code': 'IPDHRU(12)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(13) - Printed output data of HRU 13': {'code': 'IPDHRU(13)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(14) - Printed output data of HRU 14': {'code': 'IPDHRU(14)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(15) - Printed output data of HRU 15': {'code': 'IPDHRU(15)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(16) - Printed output data of HRU 16': {'code': 'IPDHRU(16)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(17) - Printed output data of HRU 17': {'code': 'IPDHRU(17)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(18) - Printed output data of HRU 18': {'code': 'IPDHRU(18)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(19) - Printed output data of HRU 19': {'code': 'IPDHRU(19)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPDHRU(20) - Printed output data of HRU 20': {'code': 'IPDHRU(20)', 'file': 'file.cio', 'inp': True, 'out': False},
             'IPHR': {'code': 'IPHR', 'file': 'file.cio', 'inp': True, 'out': False},
             'ISTO': {'code': 'ISTO', 'file': 'file.cio', 'inp': True, 'out': False},
             'ISOL': {'code': 'ISOL', 'file': 'file.cio', 'inp': True, 'out': False},
             'I_SUBW': {'code': 'I_SUBW', 'file': 'file.cio', 'inp': True, 'out': False},
             'IA_B': {'code': 'IA_B', 'file': 'file.cio', 'inp': True, 'out': False},
             'IHUMUS': {'code': 'IHUMUS', 'file': 'file.cio', 'inp': True, 'out': False},
             'ITEMP': {'code': 'ITEMP', 'file': 'file.cio', 'inp': True, 'out': False},
             'ISNOW': {'code': 'ISNOW', 'file': 'file.cio', 'inp': True, 'out': False},
             'IMGT': {'code': 'IMGT', 'file': 'file.cio', 'inp': True, 'out': False},
             'IWTR': {'code': 'IWTR', 'file': 'file.cio', 'inp': True, 'out': False},
             'ICALEN': {'code': 'ICALEN', 'file': 'file.cio', 'inp': True, 'out': False},
             'CANMX': {'code': 'CANMX', 'file': 'hru', 'inp': True, 'out': False},
             'CF': {'code': 'CF', 'file': 'hru', 'inp': True, 'out': False},
             'CFDEC': {'code': 'CFDEC', 'file': 'hru', 'inp': True, 'out': False},
             'CFH': {'code': 'CFH', 'file': 'hru', 'inp': True, 'out': False},
             'DEP_IMP': {'code': 'DEP_IMP', 'file': 'hru', 'inp': True, 'out': False},
             'DIS_STREAM': {'code': 'DIS_STREAM', 'file': 'hru', 'inp': True, 'out': False},
             'EPCO_hru': {'code': 'EPCO_hru', 'file': 'hru', 'inp': True, 'out': False},
             'ERORGN': {'code': 'ERORGN', 'file': 'hru', 'inp': True, 'out': False},
             'ERORGP': {'code': 'ERORGP', 'file': 'hru', 'inp': True, 'out': False},
             'ESCO_hru': {'code': 'ESCO_hru', 'file': 'hru', 'inp': True, 'out': False},
             'EVPOT': {'code': 'EVPOT', 'file': 'hru', 'inp': True, 'out': False},
             'FLD_FR': {'code': 'FLD_FR', 'file': 'hru', 'inp': True, 'out': False},
             'HRU_FR - Fraction of subbasin area per HRU': {'code': 'HRU_FR', 'unit':'km2/km2','file': 'hru', 'inp': True, 'out': False},
             'HRU_SLP': {'code': 'HRU_SLP', 'file': 'hru', 'inp': True, 'out': False},
             'LAT_SED': {'code': 'LAT_SED', 'file': 'hru', 'inp': True, 'out': False},
             'LAT_TTIME': {'code': 'LAT_TTIME', 'file': 'hru', 'inp': True, 'out': False},
             'N_LAG': {'code': 'N_LAG', 'file': 'hru', 'inp': True, 'out': False},
             'N_LN': {'code': 'N_LN', 'file': 'hru', 'inp': True, 'out': False},
             'N_LNCO': {'code': 'N_LNCO', 'file': 'hru', 'inp': True, 'out': False},
             'N_REDUC': {'code': 'N_REDUC', 'file': 'hru', 'inp': True, 'out': False},
             'ORGN_CON': {'code': 'ORGN_CON', 'file': 'hru', 'inp': True, 'out': False},
             'ORGP_CON': {'code': 'ORGP_CON', 'file': 'hru', 'inp': True, 'out': False},
             'OV_N': {'code': 'OV_N', 'file': 'hru', 'inp': True, 'out': False},
             'POT_FR': {'code': 'POT_FR', 'file': 'hru', 'inp': True, 'out': False},
             'POT_K': {'code': 'POT_K', 'file': 'hru', 'inp': True, 'out': False},
             'POT_NO3L': {'code': 'POT_NO3L', 'file': 'hru', 'inp': True, 'out': False},
             'POT_NSED': {'code': 'POT_NSED', 'file': 'hru', 'inp': True, 'out': False},
             'POT_SOLP': {'code': 'POT_SOLP', 'file': 'hru', 'inp': True, 'out': False},
             'POT_TILE': {'code': 'POT_TILE', 'file': 'hru', 'inp': True, 'out': False},
             'POT_VOL': {'code': 'POT_VOL', 'file': 'hru', 'inp': True, 'out': False},
             'POT_VOLX': {'code': 'POT_VOLX', 'file': 'hru', 'inp': True, 'out': False},
             'R2ADJ': {'code': 'R2ADJ', 'file': 'hru', 'inp': True, 'out': False},
             'RIP_FR': {'code': 'RIP_FR', 'file': 'hru', 'inp': True, 'out': False},
             'RSDIN': {'code': 'RSDIN', 'file': 'hru', 'inp': True, 'out': False},
             'SED_CON': {'code': 'SED_CON', 'file': 'hru', 'inp': True, 'out': False},
             'SLSOIL': {'code': 'SLSOIL', 'file': 'hru', 'inp': True, 'out': False},
             'SLSUBBSN': {'code': 'SLSUBBSN', 'file': 'hru', 'inp': True, 'out': False},
             'SOLN_CON': {'code': 'SOLN_CON', 'file': 'hru', 'inp': True, 'out': False},
             'SOLP_CON': {'code': 'SOLP_CON', 'file': 'hru', 'inp': True, 'out': False},
             'SURLAG_hru': {'code': 'SURLAG_hru', 'file': 'hru', 'inp': True, 'out': False},
             'PND_FR': {'code': 'PND_FR', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_PSA': {'code': 'PND_PSA', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_PVOL': {'code': 'PND_PVOL', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_ESA': {'code': 'PND_ESA', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_EVOL': {'code': 'PND_EVOL', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_VOL': {'code': 'PND_VOL', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_SED': {'code': 'PND_SED', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_NSED': {'code': 'PND_NSED', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_K': {'code': 'PND_K', 'file': 'pnd', 'inp': True, 'out': False},
             'IFLOD1': {'code': 'IFLOD1', 'file': 'pnd', 'inp': True, 'out': False},
             'IFLOD2': {'code': 'IFLOD2', 'file': 'pnd', 'inp': True, 'out': False},
             'NDTARG': {'code': 'NDTARG', 'file': 'pnd', 'inp': True, 'out': False},
             'PSETLP1': {'code': 'PSETLP1', 'file': 'pnd', 'inp': True, 'out': False},
             'PSETLP2': {'code': 'PSETLP2', 'file': 'pnd', 'inp': True, 'out': False},
             'NSETLP1': {'code': 'NSETLP1', 'file': 'pnd', 'inp': True, 'out': False},
             'NSETLP2': {'code': 'NSETLP2', 'file': 'pnd', 'inp': True, 'out': False},
             'CHLAP': {'code': 'CHLAP', 'file': 'pnd', 'inp': True, 'out': False},
             'SECCIP': {'code': 'SECCIP', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_NO3': {'code': 'PND_NO3', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_SOLP': {'code': 'PND_SOLP', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_ORGN': {'code': 'PND_ORGN', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_ORGP': {'code': 'PND_ORGP', 'file': 'pnd', 'inp': True, 'out': False},
             'PND_D50': {'code': 'PND_D50', 'file': 'pnd', 'inp': True, 'out': False},
             'IPND1': {'code': 'IPND1', 'file': 'pnd', 'inp': True, 'out': False},
             'IPND2': {'code': 'IPND2', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_FR': {'code': 'WET_FR', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_NSA': {'code': 'WET_NSA', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_NVOL': {'code': 'WET_NVOL', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_MXSA': {'code': 'WET_MXSA', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_MXVOL': {'code': 'WET_MXVOL', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_VOL': {'code': 'WET_VOL', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_SED': {'code': 'WET_SED', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_NSED': {'code': 'WET_NSED', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_K': {'code': 'WET_K', 'file': 'pnd', 'inp': True, 'out': False},
             'PSETLW1': {'code': 'PSETLW1', 'file': 'pnd', 'inp': True, 'out': False},
             'PSETLW2': {'code': 'PSETLW2', 'file': 'pnd', 'inp': True, 'out': False},
             'NSETLW1': {'code': 'NSETLW1', 'file': 'pnd', 'inp': True, 'out': False},
             'NSETLW2': {'code': 'NSETLW2', 'file': 'pnd', 'inp': True, 'out': False},
             'CHLAW': {'code': 'CHLAW', 'file': 'pnd', 'inp': True, 'out': False},
             'SECCIW': {'code': 'SECCIW', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_NO3': {'code': 'WET_NO3', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_SOLP': {'code': 'WET_SOLP', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_ORGN': {'code': 'WET_ORGN', 'file': 'pnd', 'inp': True, 'out': False},
             'WET_ORGP': {'code': 'WET_ORGP', 'file': 'pnd', 'inp': True, 'out': False},
             'PNDEVCOEFF': {'code': 'PNDEVCOEFF', 'file': 'pnd', 'inp': True, 'out': False},
             'WETEVCOEFF': {'code': 'WETEVCOEFF', 'file': 'pnd', 'inp': True, 'out': False},
             'CHW2': {'code': 'CHW2', 'file': 'rte', 'inp': True, 'out': False},
             'CHD': {'code': 'CHD', 'file': 'rte', 'inp': True, 'out': False},
             'CH_S2': {'code': 'CH_S2', 'file': 'rte', 'inp': True, 'out': False},
             'CH_L2': {'code': 'CH_L2', 'file': 'rte', 'inp': True, 'out': False},
             'CH_N2': {'code': 'CH_N2', 'file': 'rte', 'inp': True, 'out': False},
             'CH_K2': {'code': 'CH_K2', 'file': 'rte', 'inp': True, 'out': False},
             'CH_COV1': {'code': 'CH_COV1', 'file': 'rte', 'inp': True, 'out': False},
             'CH_COV2': {'code': 'CH_COV2', 'file': 'rte', 'inp': True, 'out': False},
             'CH_WDR': {'code': 'CH_WDR', 'file': 'rte', 'inp': True, 'out': False},
             'ALPHA_BNK': {'code': 'ALPHA_BNK', 'file': 'rte', 'inp': True, 'out': False},
             'ICANAL': {'code': 'ICANAL', 'file': 'rte', 'inp': True, 'out': False},
             'CH_ONCO': {'code': 'CH_ONCO', 'file': 'rte', 'inp': True, 'out': False},
             'CH_OPCO': {'code': 'CH_OPCO', 'file': 'rte', 'inp': True, 'out': False},
             'CH_SIDE': {'code': 'CH_SIDE', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BNK_BD': {'code': 'CH_BNK_BD', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BED_BD': {'code': 'CH_BED_BD', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BNK_KD': {'code': 'CH_BNK_KD', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BED_KD': {'code': 'CH_BED_KD', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BNK_D50': {'code': 'CH_BNK_D50', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BED_D50': {'code': 'CH_BED_D50', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BNK_TC': {'code': 'CH_BNK_TC', 'file': 'rte', 'inp': True, 'out': False},
             'CH_BED_TC': {'code': 'CH_BED_TC', 'file': 'rte', 'inp': True, 'out': False},
             'CH_EQN': {'code': 'CH_EQN', 'file': 'rte', 'inp': True, 'out': False},
             'SHALLST': {'code': 'SHALLST', 'file': 'gw', 'inp': True, 'out': False},
             'DEEPST': {'code': 'DEEPST', 'file': 'gw', 'inp': True, 'out': False},
             'GW_DELAY': {'code': 'GW_DELAY', 'file': 'gw', 'inp': True, 'out': False},
             'ALPHA_BF': {'code': 'ALPHA_BF', 'file': 'gw', 'inp': True, 'out': False},
             'GWQMN': {'code': 'GWQMN', 'file': 'gw', 'inp': True, 'out': False},
             'GW_REVAP': {'code': 'GW_REVAP', 'file': 'gw', 'inp': True, 'out': False},
             'REVAPMN': {'code': 'REVAPMN', 'file': 'gw', 'inp': True, 'out': False},
             'RCHRG_DP': {'code': 'RCHRG_DP', 'file': 'gw', 'inp': True, 'out': False},
             'GWHT': {'code': 'GWHT', 'file': 'gw', 'inp': True, 'out': False},
             'GW_SPYLD': {'code': 'GW_SPYLD', 'file': 'gw', 'inp': True, 'out': False},
             'SHALLST_N': {'code': 'SHALLST_N', 'file': 'gw', 'inp': True, 'out': False},
             'GWSOLP': {'code': 'GWSOLP', 'file': 'gw', 'inp': True, 'out': False},
             'HLIFE_NGW': {'code': 'HLIFE_NGW', 'file': 'gw', 'inp': True, 'out': False},
             'LAT_ORGN': {'code': 'LAT_ORGN', 'file': 'gw', 'inp': True, 'out': False},
             'LAT_ORGP': {'code': 'LAT_ORGP', 'file': 'gw', 'inp': True, 'out': False},
             'ALPHA_BF_D': {'code': 'ALPHA_BF_D', 'file': 'gw', 'inp': True, 'out': False},
             'RE': {'code': 'RE', 'file': 'sdr', 'inp': True, 'out': False},
             'SDRAIN': {'code': 'SDRAIN', 'file': 'sdr', 'inp': True, 'out': False},
             'DRAIN_CO': {'code': 'DRAIN_CO', 'file': 'sdr', 'inp': True, 'out': False},
             'PC': {'code': 'PC', 'file': 'sdr', 'inp': True, 'out': False},
             'LATKSATF': {'code': 'LATKSATF', 'file': 'sdr', 'inp': True, 'out': False},
             'ISEP_TYP': {'code': 'ISEP_TYP', 'file': 'sep', 'inp': True, 'out': False},
             'ISEP_IYR': {'code': 'ISEP_IYR', 'file': 'sep', 'inp': True, 'out': False},
             'ISEP_OPT': {'code': 'ISEP_OPT', 'file': 'sep', 'inp': True, 'out': False},
             'SEP_CAP': {'code': 'SEP_CAP', 'file': 'sep', 'inp': True, 'out': False},
             'BZ_AREA': {'code': 'BZ_AREA', 'file': 'sep', 'inp': True, 'out': False},
             'ISEP_TFAIL': {'code': 'ISEP_TFAIL', 'file': 'sep', 'inp': True, 'out': False},
             'BZ_Z': {'code': 'BZ_Z', 'file': 'sep', 'inp': True, 'out': False},
             'BZ_THK': {'code': 'BZ_THK', 'file': 'sep', 'inp': True, 'out': False},
             'SEP_STRM_DIST': {'code': 'SEP_STRM_DIST', 'file': 'sep', 'inp': True, 'out': False},
             'SEP_DEN': {'code': 'SEP_DEN', 'file': 'sep', 'inp': True, 'out': False},
             'BIO_BD': {'code': 'BIO_BD', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_BOD_DC': {'code': 'COEFF_BOD_DC', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_BOD_CONV': {'code': 'COEFF_BOD_CONV', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_FC1': {'code': 'COEFF_FC1', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_FC2': {'code': 'COEFF_FC2', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_FECAL': {'code': 'COEFF_FECAL', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_PLQ': {'code': 'COEFF_PLQ', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_MRT': {'code': 'COEFF_MRT', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_RSP': {'code': 'COEFF_RSP', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_SLG1': {'code': 'COEFF_SLG1', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_SLG2': {'code': 'COEFF_SLG2', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_NITR': {'code': 'COEFF_NITR', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_DENITR': {'code': 'COEFF_DENITR', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_COEFF_PDISTRB': {'code': 'COEFF_COEFF_PDISTRB', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_PSORPMAX': {'code': 'COEFF_PSORPMAX', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_SOLPSLP': {'code': 'COEFF_SOLPSLP', 'file': 'sep', 'inp': True, 'out': False},
             'COEFF_SOLPINTC': {'code': 'COEFF_SOLPINTC', 'file': 'sep', 'inp': True, 'out': False},
             'Soil Name': {'code': 'Soil Name', 'file': 'sol', 'inp': True, 'out': False},
             'Soil Hydrologic Group': {'code': 'Soil Hydrologic Group', 'file': 'sol', 'inp': True, 'out': False},
             'Maximum rooting depth(mm)': {'code': 'Maximum rooting depth(mm)', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Porosity fraction from which anions are excluded': {
                 'code': 'Porosity fraction from which anions are excluded', 'file': 'sol', 'inp': True, 'out': False},
             'Crack volume potential of soil': {'code': 'Crack volume potential of soil', 'file': 'sol', 'inp': True,
                                                'out': False},
             'Texture 1': {'code': 'Texture 1', 'file': 'sol', 'inp': True, 'out': False},
             'Depth                [mm]': {'code': 'Depth                [mm]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Bulk Density Moist [g/cc]': {'code': 'Bulk Density Moist [g/cc]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Ave. AW Incl. Rock Frag': {'code': 'Ave. AW Incl. Rock Frag', 'file': 'sol', 'inp': True, 'out': False},
             'Ksat. (est.)      [mm/hr]': {'code': 'Ksat. (est.)      [mm/hr]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Organic Carbon [weight %]': {'code': 'Organic Carbon [weight %]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Clay           [weight %]': {'code': 'Clay           [weight %]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Silt           [weight %]': {'code': 'Silt           [weight %]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Sand           [weight %]': {'code': 'Sand           [weight %]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Rock Fragments   [vol. %]': {'code': 'Rock Fragments   [vol. %]', 'file': 'sol', 'inp': True,
                                           'out': False},
             'Soil Albedo (Moist)': {'code': 'Soil Albedo (Moist)', 'file': 'sol', 'inp': True, 'out': False},
             'Erosion K': {'code': 'Erosion K', 'file': 'sol', 'inp': True, 'out': False},
             'Salinity (EC, Form 5)': {'code': 'Salinity (EC, Form 5)', 'file': 'sol', 'inp': True, 'out': False},
             'Soil pH': {'code': 'Soil pH', 'file': 'sol', 'inp': True, 'out': False},
             'Soil CACO3': {'code': 'Soil CACO3', 'file': 'sol', 'inp': True, 'out': False},
             }